meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanUpdateView,
    MealPlanDetailView,
    MealPlanListView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plan_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plan_detail"),
    path("<int:pk>/edit", MealPlanUpdateView.as_view(), name="meal_plan_edit"),
    path("new/", MealPlanCreateView.as_view(), name="meal_plan_new"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    # TagCreateView,
    # TagDeleteView,
    # TagDetailView,
    # TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    # path("<new/>", TagCreateView.as_view(), name="tags_new"), 
    # path("<int:pk>/delete/", TagDeleteView.as_view(), name="tags_delete"),
    # path("<int:pk>/", TagDetailView.as_view(), name="tags_details"),
    # path("<int:pk>/edit/", TagUpdateView.as_view(), name="tags_edit"), 
]

meal_plans/models.py
from time import timezone
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField(timezone)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", blank=True)

    def __str__(self):
        return self.name

meal_plans/views.py
from django.shortcuts import render, redirect
from meal_plans.models import MealPlan
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 5

    def list_meal_plans(request):
        context = {
            "meal_plan_list": MealPlan.objects.filter(owner=request.user)
        }
        return render(request, "meal_plans/list.html", context)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"
    context_object_name = "meal_plan_detail"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "owner", "recipes", "date"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "owner", "date", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self):
        return reverse_lazy("meal_plan_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plan_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %} {% load markdownify %}

{% block content %}
  <main class="recipe-detail">
    <div>
      <a href = "{% url 'meal_plan_edit' mealplan.id %}">{{ 'Edit' | markdownify }} </a>
      <a href = "{% url 'meal_plan_delete' mealplan.id %}">{{ 'Delete' | markdownify }} </a>
    </div>
    <h1>{{ mealplan.name }}</h1>
    <h2>by: {{ mealplan.owner | default_if_none:"Unknown" }}</h2>
    {% for recipe in mealplan.recipes.all %}
      <a href="{% url 'recipe_detail' recipe.id%}">{{ recipe.name }}</a>
    <p>
    {% endfor %}
      Date {{ mealplan.date }} |
    </p>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %} 

{% block content %}
  <main class="recipe-grid">
    {% comment %} <h1>Meal Plan Library</h1> {% endcomment %}
    {% comment %} <p></p> {% endcomment %}
      <a href = "{% url 'meal_plan_new' %}">Create</a>
    {% for mealplan in mealplan_list %}
    
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="/meal_plans/{{ mealplan.id }}">{{ mealplan.name }}</a>
        </h2>
        <h3 class="recipe-card-title">
          <a href="/recipes/{{ recipe.name }}">{{ recipe.name }}</a>
        </h3>
      </div>
      {% endfor %}
  </main>
{% endblock content %}

{% block pagination %}
  <div class="pagination">
    <footer>
      <span>
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
          <span>
            Page {{ page_obj.number }} of {{page_obj.paginator.num_pages }}
          </span>
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
      </span>
    </footer> 
  </div>
{% endblock pagination %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}

{% block content %}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}